name: server-buscaracing-admin

services:
  mysql:
    image: bitnami/mysql:8.0
    container_name: buscaracing_mysql_container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root       # Senha do root
      MYSQL_DATABASE: buscaracing_db  # Nome do banco
      MYSQL_USER: buscaracing         # Usuário
      MYSQL_PASSWORD: buscaracing     # Senha do usuário