name: server-buscaracing-admin

services:
  mysql:
    image: bitnami/mysql:8.4.4
    container_name: buscaracing_mysql_container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Senha do root
      MYSQL_DATABASE: buscaracing_db      # Nome do banco
      MYSQL_USER: user                    # Usuário
      MYSQL_PASSWORD: password            # Senha do usuário